name: Build

on:
  push:

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04

          - target: aarch64-apple-darwin
            os: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: pgextract-${{ matrix.platform.target }}
          path: pgextract